name: ROS2 CI (Humble)

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-rosdep python3-colcon-common-extensions
          sudo rosdep init || true
          rosdep update

      - name: Install deps
        run: |
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --symlink-install
